### ISSUE TITLE
tabbed box extension fails

### ISSUE THREAD

**Issue by sma00** [Neon22/inkscape-LasercutBox#1]
Extension does not work.

The zip file includes two files. python file is correct, but the inx file is called Lasercut-jigsaw.inx and is probably planned for jigsaw creation.??

**Comment by applemuncy** [comment]
Greetings sma00,

Neon22 doesn't seem to be paying any attention to his Inkscape extension
for awhile now. He does have another repository for making jigsaw puzzels
https://github.com/Neon22/inkscape-jigsaw , that seems to work fine as does
this one for making a tabbed box.

What is it that you want to do? If it is to make a tabbed box maybe you
would be interested in my work on extending the functionality of  a box
maker. I am actively working on it.
https://github.com/applemuncy/boxmaker

**Comment by sma00** [comment]
Greetings,
OK, I have meanwhile realized that the Inkscape-boxmaker is one that works. The tabbed box extension link which I tried first is in the Inkscape homepage/extensions. Perhaps that should be replaced with a working extension? Your new extension seems another choice which I may check in the future. Thanks a lot for quick answer

**Comment by ScottDWebster** [comment]
It looks like the wrong .inx file was included in the zip archive.  It includes Lasercut-box.py and Lasercut-jigsaw.inx.  The second is the exact same file included with the Lasercut_jigsaw extension (I diffed them in vim). Presumably there should have been a Lasercut-box.inx file instead.
