### ISSUE TITLE
Getting tabs inside the walls

### ISSUE THREAD

**Issue by manueldiaz96** [Neon22/inkscape-LasercutBox#2]
Sorry if this isn't the place to post this, but I also posted it in the extension at the [inkscape site.](https://inkscape.org/es/~Neon22/%E2%98%85lasercut-tabbed-box?c=1527)

I don't know if this extension is supposed to work like this, but I just downloaded it, and the two boxes I've tried to make weren't like the ones on the image on the site, they had some tabs inside.

Don't know if I'm setting something up wrong or just not seen some option.

[Settings](http://imgur.com/a/57igp)

[Result](http://imgur.com/a/gT4Ft)

Thanks a lot!

**Comment by manueldiaz96** [comment]
Just discovered it was the dividers.

Sorry!

**Comment by Neon22** [comment]
no problem
