### ISSUE TITLE
inkscape 1.0 (4035a4fb49, 2020-05-01), python3.8 - generate a box 100x50x50mm, and I receive runtime errors.

### ISSUE THREAD

**Issue by manufv** [Neon22/inkscape-LasercutBox#7]
Hi. I try to generate a box 100x50x50mm, and I received runtime errors.
see attached.

[laserboxcut errors.txt](https://github.com/Neon22/inkscape-LasercutBox/files/5080438/laserboxcut.errors.txt)

what can I do to fix it ?
i run inkscape 1.0 (4035a4fb49, 2020-05-01), python3.8

with kind regards

**Comment by manufv** [comment]
using the release https://github.com/dangrie158/inkscape-LasercutBox, it works!

**Comment by Neon22** [comment]
The dangrie version will not run in inkscape 1.0
it is designed for inkscape 0.92

**Comment by Neon22** [comment]
The code is now properly migrated and also on the inkscape extensions webpage.
Sorry about the delay.
