### ISSUE TITLE
Conflicting inx files causing failure

### ISSUE THREAD

**Issue by dakmh** [Neon22/inkscape-LasercutBox#8]
By having the dash-separated and underscore-separated versions of the .inx files reference the same file (as well as namespace, class, and extension name), Inkscape thinks it should be using the (dashed) .inx that has an annotation param, but with the (underscored) .py lacking the annotation param.  The dash-named version appears not to be working on its own at the time, anyway, so I'd recommend removing both Lasercut-box.inx and Lasercut-box.py for now, possibly moving them to a feature branch if it's still intended to be a viable variant.

**Comment by Neon22** [comment]
you are quite right. I simply forgot to remove the old files.
The extensions page on inkscape is up to date.
- https://inkscape.org/~Neon22/%E2%98%85lasercut-tabbed-box

**Comment by Neon22** [comment]
files removed
